default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: ubuntu
  password: <%= ENV['notebook_DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: notebook_development
  host: localhost
  port: 5432

test:
  <<: *default
  database: notebook_test

production:
  adapter: postgresql
  encoding: unicode
  database: notebook_production
  username: ubuntu
  password: 140099
  host: <%= ENV.fetch("NOTEBOOK_DB_HOST", "localhost") %>
  port: <%= ENV.fetch("NOTEBOOK_DB_PORT", 5432) %>
