default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: notebook_development

test:
  <<: *default
  database: notebook_test

production:
  adapter: postgresql
  encoding: unicode
  database: notebook_production
  username: <%= ENV["NOTEBOOK_DB_USER"] %>
  password: <%= ENV["NOTEBOOK_DB_PASSWORD"] %>
  host: <%= ENV.fetch("NOTEBOOK_DB_HOST", "localhost") %>
  port: <%= ENV.fetch("NOTEBOOK_DB_PORT", 5432) %>
